- name: Configure role(s) on a Windows server instance
  hosts: all
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_scheme: http
    ansible_port: 55985
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Vagrant
    ansible_password: vagrant
  tasks:

  - name: Install AD-Domain-Services feature
    ansible.windows.win_feature:
      name: AD-Domain-Services
      include_management_tools: true
      include_sub_features: true
  - name: Change the hostname
    ansible.windows.win_hostname:
      name: dc
    register: hostname
  - name: Reboot the machine if needed
    win_reboot:
     reboot_timeout: 600
     test_command: echo 'Rebooted'
     pre_reboot_delay: 5
     post_reboot_delay: 5
    register: reboot_status

  - name: Ensure the machine is back online
    wait_for_connection:
     delay: 10
     timeout: 300
    when: reboot_status.changed
  - name: Setup Active Directory Controller
    ansible.windows.win_domain:
      dns_domain_name: "killer.net"
      safe_mode_password: "Crosemont01!"
    register: active_directory_controllers
  - name: Reboot the machine if needed
    win_reboot:
     reboot_timeout: 600
     test_command: echo 'Rebooted'
     pre_reboot_delay: 5
     post_reboot_delay: 5
    register: reboot_status

  - name: Ensure the machine is back online
    wait_for_connection:
     delay: 10
     timeout: 300
    when: reboot_status.changed
