Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.cpus = "2"
    vmware.memory = "2048"
    vmware.linked_clone = false
#    vmware.clone_type = "full"
    vmware.gui = true
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-ansible.yml"
  end
end
